### ISSUE TITLE
About installing maple on nixos

### ISSUE THREAD

**Issue by huijunchen9260** [prehonor/nixscript#1]
Dear Prehonor:

I recently need to install maple on my nixos. I've searched on google and found [this thread](https://github.com/NixOS/nixpkgs/issues/97498). I have the installer and the license, but somehow the installer just cannot work successfully. Does it possible for you to provide your method to install maple on nixos?

Thank you!

Sincerely,

HJC

**Comment by prehonor** [comment]
https://github.com/prehonor/nixscript/blob/master/mathmatica.nix
nix-shell /yourpath/mathmatica.nix
cd /.../yourimqpinstallerpath
./Maple2019.0LinuxX64Installer.run
cd /yourinstalledMapleDirectory/bin
./xmaple

**Comment by prehonor** [comment]
> Dear Prehonor:
> 
> I recently need to install maple on my nixos. I've searched on google and found [this thread](https://github.com/NixOS/nixpkgs/issues/97498). I have the installer and the license, but somehow the installer just cannot work successfully. Does it possible for you to provide your method to install maple on nixos?
> 
> Thank you!
> 
> Sincerely,
> 
> HJC

https://github.com/prehonor/nixscript/blob/master/mathmatica.nix
nix-shell /yourpath/mathmatica.nix
cd /.../yourimqpinstallerpath
./Maple2019.0LinuxX64Installer.run
cd /yourinstalledMapleDirectory/bin
./xmaple

**Comment by huijunchen9260** [comment]
Thank you very much!
